// ─────────────────────────────────────────────────────────────────────────────
// framework/graphBuilder.ts
//
// GraphBuilder — the central authority for constructing a computation graph.
//
// All graph mutation flows through a single `applyOp()` method, which:
//   1. Looks up the OpSchema for the requested op.
//   2. Infers output shapes and dtypes.
//   3. Allocates new SymbolicTensors for each output.
//   4. Records a NodeIR for the compiler to consume later.
//
// The builder owns two mutable structures:
//   • A registry of all SymbolicTensors (by id).
//   • An ordered list of NodeIR records in the order they were added.
//
// `build()` snapshots the current state into a `GraphIR` value that can be
// passed to the serializer or bridge without any further mutation.
//
// Design notes:
//   • The builder does NOT import the compiler's Graph class.  It speaks only
//     the shared-ir types, keeping the frontend/backend boundary clean.
//   • IDs are generated by a simple local counter, reset to 0 per GraphBuilder
//     instance.  The bridge is responsible for mapping these to compiler IDs.
//   • Sealing prevents accidental mutations after `build()` is called.
// ─────────────────────────────────────────────────────────────────────────────

import { SymbolicTensor }           from "./tensor";
import { OpSchemaRegistry, defaultOpRegistry } from "./opRegistry";
import { GraphBuildError }          from "./errors";
import { IRDType, IRAttrs, GraphIR, TensorIR, NodeIR } from "../shared-ir/schema";
import { TensorId, NodeId, GraphId, asTensorId, asNodeId, asGraphId } from "../shared-ir/ids";
import { ShapeExpr }                from "./shape";

// ─────────────────────────────────────────────────────────────────────────────

export interface GraphBuilderOptions {
  /** Human-readable graph id.  Defaults to "main". */
  id?:          string;
  /** Op schema registry.  Defaults to the built-in default registry. */
  opRegistry?:  OpSchemaRegistry;
  /** Default dtype for new inputs/parameters when none is specified. */
  defaultDtype?: IRDType;
}

/**
 * Builds a computation graph symbolically.
 *
 * Usage:
 * ```ts
 * const gb = new GraphBuilder();
 * const x  = gb.input("x",  "float32", [32, 784]);
 * const w  = gb.param("w",  "float32", [784, 256]);
 * const b  = gb.param("b",  "float32", [256]);
 * const [mm] = gb.applyOp("matmul", [x, w]);
 * const [y]  = gb.applyOp("add",    [mm, b]);
 * const graph = gb.build();
 * ```
 */
export class GraphBuilder {
  private readonly _id:          GraphId;
  private readonly _registry:    OpSchemaRegistry;
  private readonly _defaultDtype: IRDType;

  private _tensorCounter: number = 0;
  private _nodeCounter:   number = 0;

  // Ordered lists for deterministic output
  private readonly _inputIds:  TensorId[]  = [];
  private readonly _outputIds: TensorId[]  = [];
  private readonly _nodeOrder: NodeId[]    = [];

  // Maps for lookup
  private readonly _tensors:   Map<TensorId, TensorIR>       = new Map();
  private readonly _nodes:     Map<NodeId,   NodeIR>         = new Map();
  private readonly _handles:   Map<TensorId, SymbolicTensor> = new Map();

  private _sealed: boolean = false;

  constructor(options: GraphBuilderOptions = {}) {
    this._id           = asGraphId(options.id ?? "main");
    this._registry     = options.opRegistry  ?? defaultOpRegistry;
    this._defaultDtype = options.defaultDtype ?? "float32";
  }

  // ─── ID allocation ─────────────────────────────────────────────────────────

  private _nextTensorId(): TensorId {
    return asTensorId(`t${this._tensorCounter++}`);
  }

  private _nextNodeId(): NodeId {
    return asNodeId(`n${this._nodeCounter++}`);
  }

  // ─── Guard ─────────────────────────────────────────────────────────────────

  private _assertOpen(): void {
    if (this._sealed) {
      throw new GraphBuildError(
        "GraphBuilder has been sealed by build(); no further modifications are allowed",
      );
    }
  }

  // ─── Tensor registration ───────────────────────────────────────────────────

  private _registerInputTensor(
    name:    string,
    dtype:   IRDType,
    shape:   ShapeExpr,
    isParam: boolean,
  ): SymbolicTensor {
    this._assertOpen();
    const id = this._nextTensorId();
    const tensorIR: TensorIR = {
      id,
      name,
      dtype,
      shape: [...shape],
      producerNodeId: null,
      isParam,
    };
    this._tensors.set(id, tensorIR);
    this._inputIds.push(id);
    const handle = new SymbolicTensor(id, name, dtype, shape, isParam);
    this._handles.set(id, handle);
    return handle;
  }

  // ─── Public API ────────────────────────────────────────────────────────────

  /**
   * Declare a graph-level input tensor (feeds from outside the graph at
   * runtime).  Suitable for data tensors (activations, labels).
   */
  input(
    name:  string,
    dtype: IRDType  = this._defaultDtype,
    shape: ShapeExpr = [],
  ): SymbolicTensor {
    return this._registerInputTensor(name, dtype, [...shape], false);
  }

  /**
   * Declare a trainable parameter tensor.
   * Like `input()` but `isParam` is set to true, and the tensor will be
   * included in `IRPackage.parameters` when serialized.
   */
  param(
    name:  string,
    dtype: IRDType  = this._defaultDtype,
    shape: ShapeExpr = [],
  ): SymbolicTensor {
    return this._registerInputTensor(name, dtype, [...shape], true);
  }

  /**
   * Apply an op to a list of input tensors and return the output handles.
   *
   * This is the central graph-mutation method.  It:
   *   1. Validates the op and arity.
   *   2. Runs shape + dtype inference.
   *   3. Records the node and output tensors in the IR.
   *   4. Returns one SymbolicTensor per output.
   *
   * @throws {OpError}         for unknown ops or arity mismatches.
   * @throws {ShapeError}      for incompatible shapes.
   * @throws {GraphBuildError} when called after build().
   */
  applyOp(
    op:     string,
    inputs: readonly SymbolicTensor[],
    attrs:  IRAttrs = {},
  ): SymbolicTensor[] {
    this._assertOpen();

    const inputShapes = inputs.map(t => t.shape);
    const inputDtypes = inputs.map(t => t.dtype);
    const inferred    = this._registry.infer(op, inputShapes, inputDtypes, attrs);

    const nodeId     = this._nextNodeId();
    const inputIds   = inputs.map(t => t.id);
    const outputIds: TensorId[] = [];
    const outHandles: SymbolicTensor[] = [];

    for (const out of inferred) {
      const tid = this._nextTensorId();
      const tensorIR: TensorIR = {
        id:             tid,
        name:           out.name,
        dtype:          out.dtype,
        shape:          [...out.shape],
        producerNodeId: nodeId,
      };
      this._tensors.set(tid, tensorIR);
      outputIds.push(tid);
      const handle = new SymbolicTensor(tid, out.name, out.dtype, out.shape);
      this._handles.set(tid, handle);
      outHandles.push(handle);
    }

    const nodeIR: NodeIR = {
      id:      nodeId,
      op,
      inputs:  inputIds,
      outputs: outputIds,
      attrs:   { ...attrs },
    };
    this._nodes.set(nodeId, nodeIR);
    this._nodeOrder.push(nodeId);

    return outHandles;
  }

  /**
   * Mark one or more tensors as graph-level outputs.
   * Can be called multiple times; duplicates are ignored.
   */
  markOutputs(...tensors: SymbolicTensor[]): void {
    this._assertOpen();
    for (const t of tensors) {
      if (!this._handles.has(t.id)) {
        throw new GraphBuildError(
          `markOutputs: tensor "${t.id}" (${t.name}) does not belong to this GraphBuilder`,
          { tensorId: t.id },
        );
      }
      if (!this._outputIds.includes(t.id)) {
        this._outputIds.push(t.id);
      }
    }
  }

  /**
   * Look up the SymbolicTensor handle for a given tensor id.
   * Useful when implementing the bridge or autodiff pass.
   */
  getTensorHandle(id: TensorId): SymbolicTensor {
    const h = this._handles.get(id);
    if (!h) {
      throw new GraphBuildError(`No tensor with id "${id}" in this GraphBuilder`, { id });
    }
    return h;
  }

  /** All input tensor handles in insertion order. */
  get inputs(): readonly SymbolicTensor[] {
    return this._inputIds.map(id => this._handles.get(id)!);
  }

  /** All parameter tensor handles (subset of inputs where isParam = true). */
  get params(): readonly SymbolicTensor[] {
    return this._inputIds
      .map(id => this._handles.get(id)!)
      .filter(t => t.isParam);
  }

  // ─── Snapshot ──────────────────────────────────────────────────────────────

  /**
   * Finalise the graph and return a plain-data GraphIR snapshot.
   *
   * After calling `build()` the builder is sealed: any subsequent mutation
   * attempt throws GraphBuildError.
   *
   * If no outputs have been marked, the last tensor added (i.e. the last
   * output of the last applyOp call) is implicitly used as the sole output.
   */
  build(kind: "forward" | "backward" = "forward"): GraphIR {
    this._assertOpen();

    // Auto-mark the last tensor if outputs were never explicitly set
    if (this._outputIds.length === 0) {
      if (this._nodeOrder.length === 0) {
        throw new GraphBuildError(
          "Cannot build a graph with no nodes and no outputs",
        );
      }
      const lastNode = this._nodes.get(this._nodeOrder[this._nodeOrder.length - 1])!;
      for (const tid of lastNode.outputs) {
        this._outputIds.push(tid);
      }
    }

    this._sealed = true;

    // Convert maps to plain Record objects for JSON-serializability
    const tensors: Record<TensorId, TensorIR> = {} as Record<TensorId, TensorIR>;
    for (const [id, t] of this._tensors) tensors[id] = t;

    const nodes: Record<NodeId, NodeIR> = {} as Record<NodeId, NodeIR>;
    for (const [id, n] of this._nodes) nodes[id] = n;

    const graph: GraphIR = {
      id:        this._id,
      kind,
      inputIds:  [...this._inputIds],
      outputIds: [...this._outputIds],
      nodeOrder: [...this._nodeOrder],
      tensors,
      nodes,
    };

    return graph;
  }

  /** Whether build() has been called. */
  get isSealed(): boolean { return this._sealed; }
}
